[build]
  command = "npm run build"
  publish = "build/client"

[[redirects]]
  from = "/api/*"
  to = "http://ismo.gamer.gd/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
