[build]
  command = "npm run build:server"
  publish = "build/client"
  functions = "build/server"

[[redirects]]
  from = "/api/*"
  to = "http://ismo.gamer.gd/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
